manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: corne-min-rgbled
      url: https://github.com/MechboardsLTD/zmk-module
      revision: corne-min-rgbled
    - name: corne-min-board
      url: https://github.com/MechboardsLTD/zmk-module
      revision: corne-min
    - name: prospector-module
      url: https://github.com/MechboardsLTD/zmk-module
      revision: prospector
    - name: zmk-helpers
      url: https://github.com/urob/zmk-helpers
      path: modules/zmk/helpers
      revision: 0b9e9d1dd9e86f70b4c8c2b0fab55c4f90c9d2e3

  self:
    path: config
